
services:
  api:
    image: l2ecommece:latest  # Sua nova imagem da API
    container_name: api_container
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommece
      SPRING_DATASOURCE_USERNAME: credi
      SPRING_DATASOURCE_PASSWORD: Si@010101
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db
    networks:
      - rede-app

  db:
    image: postgres:latest
    ports:
      - "5433:5432" # Mapeando a porta 5432 do container para a 5433 do host
    container_name: postgres_container_ecommece
    restart: always
    environment:
      POSTGRES_DB: ecommece
      POSTGRES_USER: credi
      POSTGRES_PASSWORD: Si@010101  # 🔥 Adicionando senha obrigatória!
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rede-app
networks:
  rede-app:
    driver: bridge
